---
apiVersion: v1
kind: Service
metadata:
  name: vpn-shoot
  namespace: kube-system
  labels:
    app: vpn-shoot
spec:
  selector:
    app: vpn-shoot
  type: LoadBalancer
  loadBalancerSourceRanges:
{{ toYaml .Values.loadBalancerSourceRanges | indent 4 }}
  ports:
  - name: openvpn
    protocol: TCP
    port: 4314
    targetPort: 1194
